# Site settings
title: Utensilios Decocina
email: utensilios.decocina.oficial@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/urban" # the subpath of your site, e.g. /blog
url: "https://bmarcos81.github.io" # the base hostname & protocol for your site
twitter_username: UDecocina
github_username:  bmarcos81

# Build settings
markdown: kramdown
permalink: pretty
